/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHome: typeof import('./src/components/AppHome.vue')['default']
    CardItem: typeof import('./src/components/CardItem.vue')['default']
    QrCodeScan: typeof import('./src/components/QrCodeScan.vue')['default']
    RegisterApplication: typeof import('./src/components/RegisterApplication.vue')['default']
    ReloadPWA: typeof import('./src/components/ReloadPWA.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./src/components/SnackBar.vue')['default']
    WindowComponent: typeof import('./src/components/WindowComponent.vue')['default']
  }
}
